### ISSUE TITLE
The core doesn't start anything

### ISSUE THREAD

**Issue by fredg20** [opengateware/arcade-irem_m92#1]
### Version (or build number)

0.1.0

### Actual Behavior

When I choose R-Type Leo, there's a loading bar and after, nothing.

**Comment by Dawbo66** [comment]
what color pocket do you have ? as some transparent might have issues.

**Comment by boogermann** [comment]
It seems like some of the transparent pocket's are having issue. Otherwise some games might take a bit to initialize, that's normal behavior.

**Comment by Skorched89** [comment]
I'm having the same issue using a transparent smoke analogue pocket.

**Comment by fredg20** [comment]
I've the Glow one

**Comment by rsn8887** [comment]
I have the same issue using a black Pocket. The loading bar finishes, then there's a black screen forever. It doesn't matter which M92 game I try. I used pupdate.exe to update.

**Comment by Truckondo** [comment]
> I have the same issue using a black Pocket. The loading bar finishes, then there's a black screen forever. It doesn't matter which M92 game I try. I used pupdate.exe to update.

Same issue here as well. Black Pocket.

**Comment by neocvera** [comment]
So far, Ive tried 
Rtype Leo
In the Hunt
Gunforce
Gunforce 2
Hook
Ninja Baseball Batman
*Games show loading bar and shifts to dark screen when complete*
kept the game(s) on for several minutes and nothing ever started up (dark screen). 

Tested on Solid Black Analogue Pocket (Late 2023 shipment) and used PUPDATE tool 

- can Quit to menu

*EDIT*
Superior Soldiers loads up with graphical issues
- does a ram loading loop, then proceeds to load warning screen along with various graphics glitches to an ultimate freeze.

Mystic Riders loads a quick ramtest (red text) then dark screen

**Comment by KClough** [comment]
The core works well on my early model black Analogue Pocket, but not my newer clear white pocket.

**Comment by ctafield** [comment]
Same issue on my glow in the dark.

**Comment by Magus667** [comment]
Same issue on my indigo limited edition

**Comment by lunchpacked130** [comment]
Have you tried with another sd card with just irem m92 or reformatted your sd card?

I can't say if that fixed it as the core was released after i started this, but i just backed up and reformatted my sdcard, and installed cores via pupdate (keeping assets and saves etc)
This fixed some small issues like sluggish menus/loading times. As well as fixing the openfpga menu taking 10-15 seconds to open each time.

Some Irem-M92 roms start immediately, and some take 6-7 seconds before showing some graphical self test or something and a few seconds more to fully load.

But the roms i have tried have worked fine.

I'm using a Translucent Red AP

![my AP running R●TYPE LEO](https://github.com/opengateware/arcade-irem_m92/assets/64440112/62703d88-3b4d-4962-b7c3-9ca437116568)

**Comment by neocvera** [comment]
> Have you tried with another sd card with just irem m92 or reformatted your sd card?
> 
> I can't say if that fixed it as the core was released after i started this, but i just backed up and reformatted my sdcard, and installed cores via pupdate (keeping assets and saves etc) This fixed some small issues like sluggish menus/loading times. As well as fixing the openfpga menu taking 10-15 seconds to open each time.
> 
> Some Irem-M92 roms start immediately, and some take 6-7 seconds before showing some graphical self test or something and a few seconds more to fully load.
> 
> But the roms i have tried have worked fine.
> 
> I'm using a Translucent Red AP
> 
> ![my AP running R●TYPE LEO](https://private-user-images.githubusercontent.com/64440112/324920507-62703d88-3b4d-4962-b7c3-9ca437116568.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTEwOTMsIm5iZiI6MTcxMzg5MDc5MywicGF0aCI6Ii82NDQ0MDExMi8zMjQ5MjA1MDctNjI3MDNkODgtM2I0ZC00OTYyLWI3YzMtOWNhNDM3MTE2NTY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE2NDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMzgxYTE2ZWZlNDc3OWJjMDQxMmIyMjk5MWE3ZWFhOWFmYjM3YjEwNTgzY2VjZjA3MzA5ZWZjNjI4M2ZlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NtHdSj4mK0iXPlLFovy5nq1i3ePywFb8MLaH_SKSUUk)

Haven’t explored that, I still have a translucent smoke to test. Funny thing is other cores seem to run no problem.

**Comment by d4z3x** [comment]
Same here with a black Analogue pocket.

**Comment by lunchpacked130** [comment]
> Haven’t explored that, I still have a translucent smoke to test. Funny thing is other cores seem to run no problem.

If you are able, find a sd card and format it, then copy over pupdate and use it to download and install the Irem-M92 core and roms and see if you still have issues

You can also try to do the APs global reset and see if it fixes anything.

I just highly doubt that it's a hardware error that suddenly only *now* and only with this core, a hardware fault shows it's actually faulty..
And i can't see how the boards in Translucent shells are different. Sure, fabrication errors do occur, but i think there would be a LOT more posts about these models having issues running cores properly if that was the case.

Correlation is not necessarily causation..

My guess is that its some sort of fragmentation error or similar, from several transfers of hundreds/thousands of rom files over time.

If a reformat / fresh new sd card and global reset doesn't work, and best case if you have a AP that confirmed runs the core, test your SD card there.
I'll also see if i can make a copy of my known working core installation during the week and upload it here for testing.

If all that fails, then it *might* indicate some other issue, but as long as its just this core, and other, more complex cores work flawlessly (amiga core for instance) then i would not bet on Analogue Pocket hardware being faulty

**Comment by ctafield** [comment]
Just updated to 0.1.1. It gets further... Seems to hang on "RAM TEST OK ROM TEST OK" on R Type Leo for me.

Update: In the hunt, and Gun Force II work now though!

**Comment by boogermann** [comment]
I just pushed an update, can you guys try v0.1.1?
https://github.com/opengateware/arcade-irem_m92/releases/download/0.1.1/opengateware.irem_m92_0.1.1_20240423-pocket.zip

**Comment by neocvera** [comment]
> I just pushed an update, can you guys try v0.1.1? https://github.com/opengateware/arcade-irem_m92/releases/download/0.1.1/opengateware.irem_m92_0.1.1_20240423-pocket.zip

I’ll give it a go in a few hours.

**Comment by Truckondo** [comment]
> I just pushed an update, can you guys try v0.1.1?
> 
> https://github.com/opengateware/arcade-irem_m92/releases/download/0.1.1/opengateware.irem_m92_0.1.1_20240423-pocket.zip

I'll give it a test after work today. Just a few hours left. 

**UPDATE**
With the latest update, I tried Baseball Ninja and R-Type Leo. Both seem to work now after a black screen lasting 10 seconds or less. I didn't try every rom but so far, this is an improvement since before it stayed on the black screen after the load happened, indefinitely.

**Comment by Dawbo66** [comment]
> I just pushed an update, can you guys try v0.1.1? https://github.com/opengateware/arcade-irem_m92/releases/download/0.1.1/opengateware.irem_m92_0.1.1_20240423-pocket.zip

works for me on my transparent pocket. Thanks

**Comment by KClough** [comment]
> I just pushed an update, can you guys try v0.1.1? https://github.com/opengateware/arcade-irem_m92/releases/download/0.1.1/opengateware.irem_m92_0.1.1_20240423-pocket.zip

Still seeing this issue on my white transparent pocket. Works on my early model black pocket, same memory card.

**Comment by ctafield** [comment]
> Just updated to 0.1.1. It gets further... Seems to hang on "RAM TEST OK ROM TEST OK" on R Type Leo for me.
> 
> Update: In the hunt, and Gun Force II work now though!

Went through all of them. Only one not working on my GITD is R Type Leo, with it hanging at the above screen.

**Comment by neocvera** [comment]
Late Model BLACK AP (late 2023) WAS NOT launching games yesterday/ Same SD card
Just merged the update over 
- Core moved to 'Arcade Multi' = makes sense
* Most games take about 10-12s to load up to a colorful static then ram check 

### _EVERY GAME LAUNCHED_
added coin, started it up, moved around a bit before testing next game.


Also Tested: Transparent Smoke model = All good!

**Comment by lunchpacked130** [comment]
I decided to do a little testing.
All current roms loads, but there are some differences
most roms have a period of black screen after loading, and all roms show graphical glitches while booting (this is fairly common for arcade roms and seems to be a graphical self test or similar)
>[!NOTE]
>Sporadically, a rom would stay at a black screen without booting or even showing graphical glitches indefinitely , but reloading the rom worked for me.

Hardware model: Translucent Red 
Memorycard: Samsung Evo Pro Plus 256gb Microsd Card
Irem/M92 Core and roms installed using Pupdate


Times are measured after rom loads (after the white bar at the bottom finishes) until "OK" screen or game boots, whichever comes first.
All load times measured at least twice and are consistent (for me at least)  


| Game Rom                       | Release v0.1.0 | Seconds of Black screen | Seconds of Graphical Glitches | 
| :--------------------------- | :--------------- | :--------------------------- | :--------------- | 
| Blade Master                    | Working          | 22 s/bs                           |  3s/gg                                       | 
| Dream Soccer  94            | Working          | 13 s/bs                            |  6 s/gg                                      | 
| Gunforce                          | Working          | 22 s/bs                            |  3 s/gg                                     | 
| Gun Force II                     | Working          | 13 s/bs                            |  6 s/gg                                     |  
| Hook                                | Working          | 15 s/bs                            |  3 s/gg                                     |  
| In the Hunt                      | Working          | 15 s/bs                            |  3 s/gg                                     |  
| Lethal Thunder                | Working          |  8 s/bs                             |  1 s/gg                                     |  
| Major Title 2                    | Working          | 14 s/bs                            | 12 s/gg                                    |  
| Mystic Riders                   | Working          |  0 s/bs                             | 31 s/gg                                    |  
| Ninja Baseball Bat Man   | Working          | 17 s/bs                            |  3 s/gg                                     |  
| R-Type LEO                     | Working          |  8 s/bs                              |  3 s/gg                                    |
| Superior Soldiers            | Working          |  4 s/bs                              |  0 s/gg                                    |   
| Undercover Cops            | Working          |  0 s/bs                             | 31 s/gg                                    |   
| Undercover Cops A.R.     | Working          |  0 s/bs                             | 25 s/gg                                    |   


> [!IMPORTANT] 
> I haven't updated the core yet, its 11pm here and my AP has 3% battery life, so ill try to have the sheet for v0.1.1 ready tomorrow


<details>
  <summary> !PLACEHOLDER! Will update list later</summary>
  

| Game Rom                       | Release v0.1.1 | Seconds of Black screen | Seconds of Graphical Glitches | 
| :--------------------------- | :--------------- | :--------------------------- | :--------------- | 
| Blade Master                    | Working          |  s/bs                           |  s/gg                                       | 
| Dream Soccer  94            | Working          |  s/bs                            |   s/gg                                      | 
| Gunforce                          | Working          |  s/bs                            |  s/gg                                     | 
| Gun Force II                     | Working          |  s/bs                            |   s/gg                                     |  
| Hook                                | Working          |  s/bs                            |   s/gg                                     |  
| In the Hunt                      | Working          |  s/bs                            |   s/gg                                     |  
| Lethal Thunder                | Working          |   s/bs                             |   s/gg                                     |  
| Major Title 2                    | Working          |  s/bs                            |  s/gg                                    |  
| Mystic Riders                   | Working          |   s/bs                             |  s/gg                                    |  
| Ninja Baseball Bat Man   | Working          |  s/bs                            |   s/gg                                     |  
| R-Type LEO                     | Working          |   s/bs                              |   s/gg                                    |
| Superior Soldiers            | Working          |   s/bs                              |   s/gg                                    |   
| Undercover Cops            | Working          |   s/bs                             |  s/gg                                    |   
| Undercover Cops A.R.     | Working          |   s/bs                             |  s/gg                                    |   

</details>

s/bs = Seconds of Black Screen.  
s/gg = Seconds of Graphical Glitches.

**Comment by lunchpacked130** [comment]
> Went through all of them. Only one not working on my GITD is R Type Leo, with it hanging at the above screen.

have you tried reloading the rom when it doesnt start? ive had some roms not load sometimes, but entering the core menu and loading the rom again has worked for me

> ### __
> added coin, started it up, moved around a bit before testing next game.
> 
> Also Tested: Transparent Smoke model = All good!

It could be coincidence, I've had roms suddenly not load as described above and in my reply above this.
but yes, this core **should** be in multi arcade, I've made a issue to reflect this

**Comment by ctafield** [comment]
> > Went through all of them. Only one not working on my GITD is R Type Leo, with it hanging at the above screen.
> 
> have you tried reloading the rom when it doesnt start? ive had some roms not load sometimes, but entering the core menu and loading the rom again has worked for me
> 

Yes, made no difference for me - every time it just hangs on the RAM TEST OK ROM TEST OK screen.

**Comment by Dawbo66** [comment]
> 
> > Went through all of them. Only one not working on my GITD is R Type Leo, with it hanging at the above screen.
> 
> have you tried reloading the rom when it doesnt start? ive had some roms not load sometimes, but entering the core menu and loading the rom again has worked for me
> 
> > ### __
> > added coin, started it up, moved around a bit before testing next game.
> > 
> > Also Tested: Transparent Smoke model = All good!
> 
> It could be coincidence, I've had roms suddenly not load as described above and in my reply above this.
> but yes, this core **should** be in multi arcade, I've made a issue to reflect this

You can add it to arcade multi yourself by changing it in platforms.

**Comment by multi-vitamin** [comment]
![0 06_to_0 07](https://github.com/opengateware/arcade-irem_m92/assets/6159122/55f63362-d0dc-479a-907f-c5aaf8734388)

Is it a board revision issue?
Main difference between the two versions is SDRAM change.

**Comment by Dahak66** [comment]
Still nothing for me using Aug 23 plain Black and Dec 23 plain White. Installed from pupdate, 0.1.1 version. SD cards tried (on both) Sandisk Ultra 1TB, and Samsung Evo Select 512GB. All games hanging at black screen after >30 seconds, but core menus accessible.

**Comment by fredg20** [comment]
> Still nothing for me using Aug 23 plain Black and Dec 23 plain White. Installed from pupdate, 0.1.1 version. SD cards tried (on both) Sandisk Ultra 1TB, and Samsung Evo Select 512GB. All games hanging at black screen after >30 seconds, but core menus accessible. 

Same

**Comment by datajerk** [comment]
2023 Black had a few issues, Apr 2024 Black, zero issues.  Moving 2024 SD (SanDisk Extreme 512GB) card to 2023 fixed all issues.  Reformatting the 2023 SD (SanDisk Extreme 64GB) card also fixed all issues.  Using `pupdate` and tested 0.1.0 and 0.1.1.

**Comment by AZRoth1968** [comment]
2023 Black Pocket, SanDisk Extreme 1tb sd card;  Updated using pupdate. Non of the games running.  Tried different SD card, 512gb Sandisk.. Still didn't work.  Everything Seems to be working now after Version 0.1.2 release!!!!

**Comment by rsn8887** [comment]
Black Pocket, using core version 0.1.1. Most times when I try to start a game, after loading, I get some Rom Test NG error message, NG means "not good."

Some times I just get an endless black screen after loading.

I got R-Type Leo to start once, just by chance, but even then it crashed during the demo gameplay. 

I tried deleting the core and assets and downloading again using latest pupdate.exe, but no change.

**Comment by PTaylor00** [comment]
None are working for me even with the update. Transparent Orange AP

**Comment by Dahak66** [comment]
Tried formatting a small card 32gb, and just installed the  irem core, and pupdate to get correct set. Still just black screen on each rom.

**Comment by Jayhawkers** [comment]
Silver AP, still black screen on each rom, regardless of SD card.

**Comment by Dahak66** [comment]
0.1.2 fixes it for me on both a mid ‘23 Black and late ‘23 White. Games working as expected now.

**Comment by ctafield** [comment]
Still the same issue with my GITD not getting past the ram/rom screen on r-type.

**Comment by ctafield** [comment]
So, interestingly, after I went in and changed a few dip switch settings (switched service mode OFF - it was previously ON, changed lives to 5, game to easy, coins to free play) - r-type now gets past the RAM/ROM screen on my GITD. I imagine out of them its likely to have been the service mode?

**Comment by Dawbo66** [comment]
Have you tried the 1.2 beta ? this seems to be working.

**Comment by Two4Five** [comment]
I was among the ones having issues with the first 2 versions - graphic corruption or no start at all (Gun Soldier), loss of sound followed by core crash (ie In the Hunt, R-type Leo). The 0.1.2 fixes all of that so far (still not done testing all games). Thanks for all the work. If it may be of any help I've noticed similar graphical corruption on the Analogue Pocket on the last public version of Jotego OutRun - going back to previous release solved it but according to Jotego this was due to some timing issues in the core that only happen to some A Pockets hardware.

**Comment by rsn8887** [comment]
The latest release 0.1.2 fixed my problems with ROM NG messages and hanging on startup as well.

**Comment by mddifilippo89** [comment]
> The latest release 0.1.2 fixed my problems with ROM NG messages and hanging on startup as well.

I put in another issue where there are still rom/ram messages and freezing after the update.
https://github.com/opengateware/arcade-irem_m92/issues/9
